/* eslint-disable @typescript-eslint/no-explicit-any */
// BUG FIX (audit round 3, "Bonus check" item): BankUploadService existed with
// fully-working Excel/CSV/Text/JSON-lines/Word bulk-question-import logic
// (validation, duplicate detection, reference-ID checks, audit logging) but
// was NEVER registered as a provider anywhere and NO controller exposed it.
// Every "upload questions" template the admin could download
// (GET /admin/help/templates/*) had nothing on the other end to receive the
// filled-in file — the whole bulk-upload feature was dead on arrival.
// This controller wires it up for real, admin/moderator-only.
import {
  Controller,
  Post,
  UseGuards,
  UseInterceptors,
  UploadedFile,
  Body,
  Req,
  BadRequestException,
} from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { JwtAuthGuard } from '../common/guards/jwt-auth.guard';
import { RolesGuard } from '../common/guards/roles.guard';
import { Roles } from '../common/decorators/roles.decorator';
import { BankUploadService } from './bank-upload.service';

const MAX_UPLOAD_BYTES = 20 * 1024 * 1024; // 20MB — question files are text/spreadsheets, not media

@Controller('bank/admin/upload')
@UseGuards(JwtAuthGuard, RolesGuard)
@Roles('ADMIN', 'MODERATOR')
export class BankUploadController {
  constructor(private readonly uploadService: BankUploadService) {}

  private adminId(req: any): string {
    return req.user?.userId ?? req.user?.id;
  }

  @Post('excel')
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: MAX_UPLOAD_BYTES } }))
  async uploadExcel(@UploadedFile() file: any, @Req() req: any) {
    if (!file) throw new BadRequestException('Multipart field "file" (.xlsx/.xls) is required');
    return this.uploadService.uploadFromExcel(file.buffer, this.adminId(req));
  }

  @Post('csv')
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: MAX_UPLOAD_BYTES } }))
  async uploadCsv(@UploadedFile() file: any, @Req() req: any) {
    if (!file) throw new BadRequestException('Multipart field "file" (.csv) is required');
    return this.uploadService.uploadFromCSV(file.buffer, this.adminId(req));
  }

  // Accepts both tab-separated .txt files AND raw JSON-array .json/.txt files —
  // BankUploadService.uploadFromText() already auto-detects JSON vs tab-separated.
  @Post('text')
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: MAX_UPLOAD_BYTES } }))
  async uploadText(@UploadedFile() file: any, @Req() req: any) {
    if (!file) throw new BadRequestException('Multipart field "file" (.txt/.json) is required');
    return this.uploadService.uploadFromText(file.buffer, this.adminId(req));
  }

  // Same handler as /text but named for clarity when the admin picks "JSON file" in the UI.
  @Post('json')
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: MAX_UPLOAD_BYTES } }))
  async uploadJsonFile(@UploadedFile() file: any, @Req() req: any) {
    if (!file) throw new BadRequestException('Multipart field "file" (.json) is required');
    return this.uploadService.uploadFromText(file.buffer, this.adminId(req));
  }

  // Paste-in JSON (no file) — e.g. admin copy-pastes an array of question
  // objects generated by an AI prompt straight into a textarea.
  @Post('json-paste')
  async uploadJsonPaste(@Body() body: any, @Req() req: any) {
    const questions = Array.isArray(body) ? body : body?.questions;
    if (!Array.isArray(questions) || questions.length === 0) {
      throw new BadRequestException('Body must be a JSON array of questions, or { "questions": [...] }');
    }
    const buffer = Buffer.from(JSON.stringify(questions), 'utf-8');
    return this.uploadService.uploadFromText(buffer, this.adminId(req));
  }

  @Post('word')
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: MAX_UPLOAD_BYTES } }))
  async uploadWord(@UploadedFile() file: any, @Req() req: any) {
    if (!file) throw new BadRequestException('Multipart field "file" (.docx) is required');
    return this.uploadService.uploadFromWord(file.buffer, this.adminId(req));
  }
}
