-- BUGFIX (Sachin's audit, Sep 2026 session) — "column questionImageUrl does
-- not exist in the current database" on every single bulk-upload row.
--
-- Root cause: schema.prisma (Session 24 comment, line ~395) declares
-- `questionImageUrl String?` on the Question model, and
-- backend/src/bank/bank-upload.service.ts's createQuestion() has ALWAYS
-- written this field on every prisma.question.create() call. But the
-- migration that shipped alongside Session 24's feature
-- (20260902_add_question_diagram_fields) only added the TWO Venn-diagram
-- columns (questionDiagramType, questionDiagramLabels) — it never added
-- questionImageUrl itself. So the Prisma Client (generated from
-- schema.prisma) has always "believed" this column exists, while the real
-- Postgres database never actually got it. Every create() — Excel, CSV,
-- JSON, Text, Word, ALL of them, since they all funnel through the same
-- createQuestion() — has been failing with exactly this error.
--
-- Fix: add the missing column. Nullable + no default, so this is purely
-- additive — every existing row and every existing feature (Venn diagrams,
-- video solutions, verification pipeline, etc.) is completely unaffected.
-- IF NOT EXISTS makes this safe to run even if it was ever partially
-- applied by hand.

ALTER TABLE "questions" ADD COLUMN IF NOT EXISTS "questionImageUrl" TEXT;
